version: "3.8"

services:
    webporto_app:
        build:
            context: .
            dockerfile: Dockerfile
        image: ${DOCKER_USERNAME:-local}/${IMAGE_NAME:-webporto}:latest
        container_name: ${IMAGE_NAME:-webporto_app}
        restart: unless-stopped
        ports:
            - "8080:80"
        networks:
            - proxy
            - internal_net
        env_file:
            - .env
        deploy:
            resources:
                limits:
                    memory: 256M
                    cpus: '0.5'

networks:
    proxy:
        external: true
    internal_net:
        driver: bridge
