name: Pull to VPS

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Debug Secrets
      run: |
        echo "VPS_HOST: ${{ secrets.VPS_HOST }}"

    - name: Execute SSH Command on VPS
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        password: ${{ secrets.VPS_PASSWORD }}
        port: ${{ secrets.VPS_PORT }}
        script: |
          echo "Connect to VPS with SSH"
          cd /home/workspace/web-porto
          git pull origin master
        debug: true
